

name: bz2
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm package
        run: |
          npm install
      - name: Download artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts \
            | jq '.artifacts[] | .id' | xargs -I {} curl -H "Authorization: Bearer $GITHUB_TOKEN" \
            -L https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}/zip -o artifact.zip
          unzip artifact.zip
          ls -l
      - name: Run plugin test
        run: |
          node test/test.mjs ${{ github.workflow }}